version: 2.1

orbs:
  win: circleci/windows@2.2.0
  
  jobs:
    build: hello world
      executor:
        name: win/default
        size: "medium"
        
     steps: 
     - checkout
     - run: Write-Host 'Hello Windows World'
